apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "dranet.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dranet.labels" . | nindent 4 }}
    tier: node
    app: {{ include "dranet.name" . }}
    k8s-app: {{ include "dranet.name" . }}
spec:
  selector:
    matchLabels:
      {{- include "dranet.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "dranet.labels" . | nindent 8 }}
        {{- include "dranet.selectorLabels" . | nindent 8 }}
        tier: node
        k8s-app: {{ include "dranet.name" . }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      hostNetwork: true
      serviceAccountName: {{ include "dranet.serviceAccountName" . }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      containers:
        - name: dranet
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - /dranet
            - --v={{ .Values.logVerbosity }}
            - --hostname-override=$(NODE_NAME)
            {{- if .Values.metricsPort }}
            - --bind-address=:{{ .Values.metricsPort }}
            {{- end }}
            {{- if .Values.args.filter }}
            - {{ print "--filter=" .Values.args.filter | quote }}
            {{- end }}
            {{- if .Values.args.inventoryMinPollInterval }}
            - --inventory-min-poll-interval={{ .Values.args.inventoryMinPollInterval }}
            {{- end }}
            {{- if .Values.args.inventoryMaxPollInterval }}
            - --inventory-max-poll-interval={{ .Values.args.inventoryMaxPollInterval }}
            {{- end }}
            {{- if .Values.args.inventoryPollBurst }}
            - --inventory-poll-burst={{ .Values.args.inventoryPollBurst }}
            {{- end }}
            {{- if (hasKey .Values.args "moveIBInterfaces") }}
            - --move-ib-interfaces={{ .Values.args.moveIBInterfaces }}
            {{- end }}
            {{- if .Values.args.cloudProviderHint }}
            - --cloud-provider-hint={{ .Values.args.cloudProviderHint }}
            {{- end }}
            - --kubelet-root-dir={{ .Values.kubeletRootDir }}
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          resources:
            requests:
              {{- toYaml .Values.resources.requests | nindent 14 }}
            {{- with .Values.resources.limits }}
            limits:
              {{- toYaml . | nindent 14 }}
            {{- end }}
          securityContext:
            privileged: true
          startupProbe:
            httpGet:
              path: {{ .Values.metricsPath }}
              port: {{ .Values.metricsPort | default 9177 }}
            failureThreshold: 12
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: {{ .Values.metricsPath }}
              port: {{ .Values.metricsPort | default 9177 }}
          volumeMounts:
            - name: device-plugin
              mountPath: {{ .Values.kubeletRootDir }}/plugins
            - name: plugin-registry
              mountPath: {{ .Values.kubeletRootDir }}/plugins_registry
            - name: nri-plugin
              mountPath: /var/run/nri
            - name: netns
              mountPath: /var/run/netns
              mountPropagation: HostToContainer
            - name: infiniband
              mountPath: /dev/infiniband
              mountPropagation: HostToContainer
            - name: bpf-programs
              mountPath: /sys/fs/bpf
              mountPropagation: HostToContainer
      volumes:
        - name: device-plugin
          hostPath:
            path: {{ .Values.kubeletRootDir }}/plugins
        - name: plugin-registry
          hostPath:
            path: {{ .Values.kubeletRootDir }}/plugins_registry
        - name: nri-plugin
          hostPath:
            path: /var/run/nri
        - name: netns
          hostPath:
            path: /var/run/netns
        - name: infiniband
          hostPath:
            path: /dev/infiniband
        - name: bpf-programs
          hostPath:
            path: /sys/fs/bpf
