apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - device-class.yaml
  - resource-claim-template.yaml

configMapGenerator:
  - name: pytorch-nccl-mfu-benchmark
    files:
      - mfu_benchmark.py
      - launcher-4gpu.sh
      - worker-sshd.sh

generatorOptions:
  disableNameSuffixHash: true
