apiVersion: multitenancy.acn.azure.com/v1alpha1
kind: PodNetwork
metadata:
    name: cust-pn3
spec:
    networkID: 9b9d4ab4-4ed8-4bfa-99b4-ce9d29f730f0
    deviceType: "acn.azure.com/vnet-nic"
    subnetGUID: "d8311b87-48cd-4803-9912-26288c4e9cde"
    subnetResourceID: /subscriptions/37deca37-c375-4a14-b90a-043849bd2bf1/resourceGroups/poddensityeuap/providers/Microsoft.Network/virtualNetworks/customervnet/subnets/dedicatedsubnet3
