apiVersion: v1
kind: Pod
metadata:
  name: sharedpod3
  namespace: default
  labels:
    kubernetes.azure.com/pod-network-instance: cust-pni
spec:
  containers:
  - name: nginx
    image: nginx:1.25
    ports:
    - containerPort: 80
    resources:
      claims:
      - name: pod-net

  resourceClaims:
  - name: pod-net
    resourceClaimTemplateName: cxsub-shared-rct