
apiVersion: v1
kind: Pod
metadata:
  name: vnetpod11
  labels:
    kubernetes.azure.com/pod-network-instance: cust-pni
spec:
  #nodeName: aks-nodes-85691567-vmss000001
  nodeSelector:
    "kubernetes.io/os": linux
  containers:
  - name: azure-linux
    image: weibeld/ubuntu-networking
    command: ["/bin/sh", "-c"]
    args: ["while true; do echo 'Hello this is LCOW container on AKS Windows'; ps -efj; uname -a; sleep 5; done"]
    resources:
      limits:
        cpu: 300m
        memory: 600Mi
      requests:
        cpu: 300m
        memory: 600Mi
    securityContext:
      privileged: true