apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Pod","metadata":{"annotations":{"multitenancy.acn.azure.com/podNetwork":"pn-pon-test"},"name":"nginx-pn-test","namespace":"default"},"spec":{"containers":[{"image":"nginx:1.25","name":"nginx","ports":[{"containerPort":80}],"resources":{"claims":[{"name":"pod-net"}]}}],"resourceClaims":[{"name":"pod-net","resourceClaimTemplateName":"pod-subnet-shared-rct"}]}}
    multitenancy.acn.azure.com/podNetwork: pn-pon-test
  creationTimestamp: "2026-04-07T23:07:52Z"
  generation: 1
  name: nginx-pn-test
  namespace: default
  resourceVersion: "2814701"
  uid: 79b131d3-657a-427c-a113-e9f8a8f90961
spec:
  containers:
  - image: nginx:1.25
    imagePullPolicy: IfNotPresent
    name: nginx
    ports:
    - containerPort: 80
      protocol: TCP
    resources:
      claims:
      - name: pod-net
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-m9hx4
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: aks-nodes-20340232-vmss000000
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  resourceClaims:
  - name: pod-net
    resourceClaimTemplateName: pod-subnet-shared-rct
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-m9hx4
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2026-04-07T23:14:36Z"
    observedGeneration: 1
    status: "False"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2026-04-07T23:14:36Z"
    observedGeneration: 1
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2026-04-07T23:14:36Z"
    message: 'containers with unready status: [nginx]'
    observedGeneration: 1
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2026-04-07T23:14:36Z"
    message: 'containers with unready status: [nginx]'
    observedGeneration: 1
    reason: ContainersNotReady
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2026-04-07T23:14:36Z"
    observedGeneration: 1
    status: "True"
    type: PodScheduled
  containerStatuses:
  - image: nginx:1.25
    imageID: ""
    lastState: {}
    name: nginx
    ready: false
    restartCount: 0
    started: false
    state:
      waiting:
        reason: ContainerCreating
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-m9hx4
      readOnly: true
      recursiveReadOnly: Disabled
  hostIP: 10.224.0.12
  hostIPs:
  - ip: 10.224.0.12
  observedGeneration: 1
  phase: Pending
  qosClass: BestEffort
  resourceClaimStatuses:
  - name: pod-net
    resourceClaimName: nginx-pn-test-pod-net-knc7v
  startTime: "2026-04-07T23:14:36Z"