apiVersion: resource.k8s.io/v1
kind: ResourceClaimTemplate
metadata:
  name: pod-subnet-shared-rct
  namespace: default
spec:
  spec:
    devices:
      requests:
      - name: nic
        firstAvailable:
        - name: preferred-nic
          deviceClassName: swift-shared-nic-matching-pod-subnet
          count: 1
        - name: fallback-nic
          deviceClassName: swift-shared-nic-pristine
          count: 1
      config:
      - requests: [ "nic" ]
        opaque:
          driver: networking.azure.com
          parameters:
            deviceType: acn.azure.com/vnet-nic
            networkID: 11ab862b-8f4b-43b1-9224-c4da60ab7b04
            subnetResourceID: /subscriptions/37deca37-c375-4a14-b90a-043849bd2bf1/resourceGroups/MC_poddensitytesting_infrastamp_westus2/providers/Microsoft.Network/virtualNetworks/aks-vnet-39571750/subnets/pod-subnet
            subnetAllocationMode: PrefixBlock
