apiVersion: v1
kind: Pod
metadata:
  name: swiftv1pod
  namespace: default
spec:
  containers:
  - name: netshoot
    image: nicolaka/netshoot:latest
    resources:
      limits:
        acn.azure.com/vnet-nic: "1"
    command: [ "sleep", "infinity" ]
    securityContext:
      privileged: true
      capabilities:
        add: [ "NET_ADMIN", "NET_RAW", "SYS_ADMIN", "SYS_PTRACE" ]
