apiVersion: v2
name: dranet
description: Helm chart for deploying DRANET, a Kubernetes network driver using Dynamic Resource Allocation (DRA)
type: application
version: 0.1.0
appVersion: "stable"
home: https://github.com/kubernetes-sigs/dranet
sources:
  - https://github.com/kubernetes-sigs/dranet
keywords:
  - networking
  - dra
  - dynamic-resource-allocation
maintainers:
  - name: aojea
  - name: gauravkghildiyal
  - name: michaelasp
  - name: fmuyassarov
